import{a as $,S as B,i as a}from"./assets/vendor-DvfmeZXB.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&s(u)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const H="https://pixabay.com/api/",_="53365045-d30e2460a35774e20f4e732a7",h=15;async function b(e,r=1){const n=new URLSearchParams({key:_,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:h,page:r}),s=`${H}?${n.toString()}`;return(await $.get(s)).data}const L=document.querySelector(".gallery"),i=document.querySelector(".loader"),p=document.querySelector(".load-more"),S="is-shown",w="is-hidden";let l=null;function C(){l?l.refresh():l=new B(".gallery a",{captionsData:"alt",captionDelay:250})}function v(e){if(!Array.isArray(e)||e.length===0)return;const r=e.map(({webformatURL:n,largeImageURL:s,tags:t,likes:o,views:u,comments:R,downloads:I})=>`<li class="gallery-item">
          <a class="gallery-link" href="${s}">
            <img class="gallery-image" src="${n}" alt="${t}" loading="lazy" />
          </a>
          <div class="image-stats">
            <p class="stat">Likes <span>${o}</span></p>
            <p class="stat">Views <span>${u}</span></p>
            <p class="stat">Comments <span>${R}</span></p>
            <p class="stat">Downloads <span>${I}</span></p>
          </div>
        </li>`).join("");L.insertAdjacentHTML("beforeend",r),C()}function D(){L.innerHTML="",l&&(l.destroy(),l=null)}function E(){i&&(i.classList.add(S),i.setAttribute("aria-hidden","false"))}function A(){i&&(i.classList.remove(S),i.setAttribute("aria-hidden","true"))}function q(){p&&p.classList.remove(w)}function f(){p&&p.classList.add(w)}function M(){const e=L.querySelector(".gallery-item");if(!e)return 0;const{height:r}=e.getBoundingClientRect();return r}const g=document.querySelector(".form"),m=g.querySelector("button[type=submit]"),P=g.querySelector('input[name="search-text"]'),O=document.querySelector(".load-more");let y="",c=1,d=0;m.disabled=!0;P.addEventListener("input",e=>{m.disabled=e.target.value.trim()===""});g.addEventListener("submit",async e=>{e.preventDefault();const r=P.value.trim();if(!r){a.warning({title:"Warning",message:"Please enter a search query",position:"topRight"});return}y=r,c=1,d=0,D(),f(),E(),m.disabled=!0;try{const n=await b(y,c),s=n.hits;if(d=n.totalHits||0,!s.length){a.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}v(s),d>c*h?q():(f(),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(n){console.error(n),a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{A(),g.reset(),m.disabled=!0}});O.addEventListener("click",async()=>{c+=1,E(),f();try{const e=await b(y,c),r=e.hits;v(r),c*h>=(e.totalHits||d)?(f(),a.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):q();const s=M();s&&window.scrollBy({top:s*2,behavior:"smooth"})}catch(e){console.error(e),a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{A()}});
//# sourceMappingURL=index.js.map
